name: CI Cron
  # You may pin to the exact commit or the version.
  # uses: kategengler/ci-cron@181db7e5bac13d0b55b6f5c4a8567fd20154576b
  uses: kategengler/ci-cron@v1.0.3
  with:
    # Branch to run CI on
    branch: 
    # Personal access token with repo scope
    personal_token: 
    # Email to use for the commit, defaults to cron@example.org
    committer_email: # optional, default is cron@example.org
    # Name to use for the commit, defaults to Cron CI
    committer_name: # optional, default is Cron CI
    # Prefix to use for the branch, defaults to cron-
    branch_prefix: # optional, default is cron-
    # Prefix to use for the commit message, defaults to Cron
    commit_message_prefix: # optional, default is Cron

name: main
on:
  workflow_dispatch:
  # push:
  schedule:
    - cron: '10 17 * * *'
permissions:
  contents: read
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v6
      - name: 创建node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json
      - name: 🔧 检查GitHub CLI
        run: |
          if ! command -v gh >/dev/null 2>&1; then
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
            sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
            sudo apt update
            sudo apt install gh -y
          fi
          gh --version
      - name: Cache node_modules in api directory
        id: cache-npm
        uses: actions/cache@v5
        with:
          path: ./api/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./api/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: 安装依赖
        run: cd api && npm ci --no-fund --no-audit
        if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      - name: 签到
        run: npm run main
        env:
          USERINFO: ${{ secrets.USERINFO }}
          PAT: ${{ secrets.PAT }}
          GITHUB_REPOSITORY: ${{ github.repository }}
